"""Added last_like_date and daily_likes_count fields to Participant

Revision ID: 1df4d1111803
Revises: f0b1e055b0fa
Create Date: 2024-10-30 12:36:57.355889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df4d1111803'
down_revision: Union[str, None] = 'f0b1e055b0fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('last_like_date', sa.Date(), nullable=True))
    op.add_column('participants', sa.Column('daily_likes_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'daily_likes_count')
    op.drop_column('participants', 'last_like_date')
    # ### end Alembic commands ###
