"""Added latitude and longitude fields to Participant

Revision ID: 491423c8eaa7
Revises: 0224f5c2ee49
Create Date: 2024-10-30 13:42:18.665745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '491423c8eaa7'
down_revision: Union[str, None] = '0224f5c2ee49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
