"""Added likes and mutual_like_id fields to Participant

Revision ID: f0b1e055b0fa
Revises: d9766dc11b58
Create Date: 2024-10-30 12:29:20.211742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0b1e055b0fa'
down_revision: Union[str, None] = 'd9766dc11b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('participants', sa.Column('mutual_like_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'participants', 'participants', ['mutual_like_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.drop_column('participants', 'mutual_like_id')
    op.drop_column('participants', 'likes')
    # ### end Alembic commands ###
